First step towards pipenv
a1rw4lk/sskmAnalyser pull request #1
Opened 2020-04-08 11:10 UTC by TimotheusBachinger

* Use pipenv to isolate python environment
* Makefile with basic target exists

2020-04-11 09:41 UTC, a1rw4lk requested changes

2020-04-11 09:41 UTC, a1rw4lk commented on Makefile
> +	pipenv install
I have to run `pipenv install --python=python3` on my setup. I'm running under WSL, and at some point pipenv install wants to execute the python.exe under Windows if I don't pass the `--python=python3` argument. Dunno why though, but passing the additional argument doesn't hurt, right?

2020-04-11 09:41 UTC, a1rw4lk commented on Makefile
> +	sudo -H pip install -U pipenv
`sudo -H pip3 install -U pipenv`
Or is there a better way to use pip3? Maybe setting it to default in the env.make?

2020-04-11 09:43 UTC, a1rw4lk commented
Nice work though :D Thanks for contributing <3

2020-04-15 06:04 UTC, TimotheusBachinger commented on Makefile
> +	sudo -H pip install -U pipenv
should not be needed when using pipenv install --python=python3

2020-04-15 06:04 UTC, TimotheusBachinger commented on Makefile
> +	pipenv install
done

2020-04-15 07:16 UTC, merged